name: liblsl_coordinator
description: A performance-focused Dart (and Flutter) LSL-based device coordination library.
version: 0.0.5+0
homepage: https://zeyus.com/
repository: https://github.com/NexusDynamic/liblsl.dart
issue_tracker: https://github.com/NexusDynamic/liblsl.dart/issues
# for now, we aren't publishing, it needs to use an available LSL version
# not from path.
publish_to: 'none'

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  # liblsl: ^0.9.0
  liblsl:
    path: ../liblsl
  synchronized: ^3.4.0
  logging: ^1.3.0
  uuid: ^4.5.1
  collection: ^1.19.1
  fast_immutable_collections: ^11.1.0
  # path: ^1.8.0

dev_dependencies:
  integration_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.24.0
