name: liblsl
description: A Dart (and Flutter) native library for working with Lab Streaming Layer (LSL / liblsl).
version: 0.10.1+0
homepage: https://zeyus.com/
repository: https://github.com/NexusDynamic/liblsl.dart
issue_tracker: https://github.com/NexusDynamic/liblsl.dart/issues

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  ffi: ^2.1.4
  hooks: ^1.0.0
  native_toolchain_c: ^0.17.2
  code_assets: ^1.0.0
  logging: ^1.3.0
  meta: ^1.16.0
  fast_immutable_collections: ^11.1.0

dev_dependencies:
  ffigen: ^20.0.0
  lints: ^6.0.0
  test: ^1.26.0
  dartdoc: ^9.0.0

ffigen:
  name: Liblsl
  silence-enum-warning: true
  ffi-native:
  description: Bindings to `lsl_c.h`.
  output: 'lib/native_liblsl.dart'
  headers:
    entry-points:
      - 'src/liblsl-846c4199/include/lsl_c.h'
    include-directives:
      - 'src/liblsl-846c4199/include/lsl/*.h'
      - 'src/liblsl-846c4199/include/lsl_c.h'
  compiler-opts:
    - '-Isrc/liblsl-846c4199/include'
  structs:
    dependency-only: opaque
  functions:
    expose-typedefs:
      include:
        - '.*'
